// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8HVHy-bNjSpopkToyineY5u42uJ1Fj2w',
    appId: '1:480416527325:web:6109997359267f922abc34',
    messagingSenderId: '480416527325',
    projectId: 'shift-manager-3f19f',
    authDomain: 'shift-manager-3f19f.firebaseapp.com',
    storageBucket: 'shift-manager-3f19f.firebasestorage.app',
    measurementId: 'G-C9X8QWMH4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzWtG9LhdpNGQYPKKgvfzTBBK-yMNrjaI',
    appId: '1:480416527325:android:1c27e6592b1497bf2abc34',
    messagingSenderId: '480416527325',
    projectId: 'shift-manager-3f19f',
    storageBucket: 'shift-manager-3f19f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3CLF3GMAqI5LsDB7Xdv0-Bq5TjqGG5j0',
    appId: '1:480416527325:ios:5adc8e571838955b2abc34',
    messagingSenderId: '480416527325',
    projectId: 'shift-manager-3f19f',
    storageBucket: 'shift-manager-3f19f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3CLF3GMAqI5LsDB7Xdv0-Bq5TjqGG5j0',
    appId: '1:480416527325:ios:5adc8e571838955b2abc34',
    messagingSenderId: '480416527325',
    projectId: 'shift-manager-3f19f',
    storageBucket: 'shift-manager-3f19f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8HVHy-bNjSpopkToyineY5u42uJ1Fj2w',
    appId: '1:480416527325:web:259c804fa4351fdb2abc34',
    messagingSenderId: '480416527325',
    projectId: 'shift-manager-3f19f',
    authDomain: 'shift-manager-3f19f.firebaseapp.com',
    storageBucket: 'shift-manager-3f19f.firebasestorage.app',
    measurementId: 'G-1QZ27GG4PN',
  );
}
